---
settings:
  parallel: true

driver:
  name: vagrant

provisioner:
  name: chef_zero
  # https://github.com/chef/chef/issues/5362
  chef_omnibus_install_options: -c current
  # our tmp.mount test unit masks default /tmp path on ubuntu
  root_path: /var/tmp/kitchen

verifier:
  name: inspec

platforms:
  - name: centos-7.2
  - name: fedora-24
  - name: debian-8.5
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[test::default]
    attributes:
      systemd:
        hostname: my-hostname
