---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: fedora-21

suites:
  - name: resources
    run_list:
      - recipe[setup]
  - name: daemons
    run_list:
      - recipe[systemd::journal_gatewayd]
      - recipe[systemd::journald]
      - recipe[setup::journald]
      - recipe[systemd::logind]
      - recipe[setup::logind]
      - recipe[systemd::networkd]
      - recipe[systemd::resolved]
      - recipe[setup::resolved]
      - recipe[systemd::timesyncd]
      - recipe[setup::timesyncd]
  - name: utils
    run_list:
      - recipe[systemd::bootchart]
      - recipe[systemd::coredump]
      - recipe[systemd::locale]
      - recipe[systemd::hostname]
      - recipe[systemd::machined]
      - recipe[systemd::sleep]
      - recipe[systemd::sysctl]
      - recipe[setup::sysctl]
      - recipe[systemd::system]
      - recipe[systemd::timedated]
      - recipe[setup::tmpfiles]
      - recipe[systemd::udev]
      - recipe[systemd::user]
      - recipe[systemd::vconsole]
