---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: fedora-24
  - name: ubuntu-16.04
  - name: debian-8.5
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[setup::units]
      - recipe[setup::daemons]
      - recipe[setup::misc]
