---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: fedora-21

suites:
  - name: resources
    run_list:
      - recipe[systemd]
      - recipe[setup]
  - name: daemons
    run_list:
      - recipe[systemd::timesyncd]
      - recipe[setup::timesyncd]
      - recipe[systemd::journald]
      - recipe[setup::journald]
      - recipe[systemd::logind]
      - recipe[setup::logind]
      - recipe[systemd::resolved]
      - recipe[setup::resolved]
      - recipe[systemd::hostnamed]
      - recipe[systemd::journal_gatewayd]
