---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: fedora-22
  - name: ubuntu-15.04
  - name: debian-8.2
  - name: centos-7.1

suites:
  - name: units
    run_list:
      - recipe[setup::automount]
      - recipe[setup::mount]
      - recipe[setup::networkd_link]
      - recipe[setup::path]
      - recipe[setup::service]
      - recipe[setup::slice]
      - recipe[setup::socket]
      - recipe[setup::swap]
      - recipe[setup::target]
      - recipe[setup::timer]
  - name: daemons
    run_list:
      - recipe[systemd::journald]
      - recipe[setup::journald]
      - recipe[systemd::logind]
      - recipe[setup::logind]
      - recipe[systemd::machined]
      - recipe[systemd::timedated]
  - name: daemons-new
    excludes:
      - ubuntu-15.04
      - debian-8.1
      - centos-7.1
    run_list:
      - recipe[systemd::journal_gatewayd]
      - recipe[systemd::networkd]
      - recipe[systemd::resolved]
      - recipe[setup::resolved]
      - recipe[systemd::timesyncd]
      - recipe[setup::timesyncd]
  - name: utils
    run_list:
      - recipe[systemd::bootchart]
      - recipe[systemd::coredump]
      - recipe[systemd::locale]
      - recipe[systemd::hostname]
      - recipe[setup::modules]
      - recipe[systemd::real_time_clock]
      - recipe[systemd::sleep]
      - recipe[systemd::sysctl]
      - recipe[setup::sysctl]
      - recipe[systemd::system]
      - recipe[systemd::timezone]
      - recipe[setup::tmpfiles]
      - recipe[systemd::udevd]
      - recipe[setup::udev]
      - recipe[systemd::user]
    attributes:
      systemd:
        udev:
          options:
            children-max: 10
  - name: utils-new
    excludes:
      - debian-8.1
      - centos-7.1
      - ubuntu-15.04
    run_list:
      - recipe[systemd::vconsole]
      - recipe[systemd::binfmt]
      - recipe[setup::binfmt]
      - recipe[systemd::sysusers]
      - recipe[setup::sysuser]
