---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-15.04
  - name: debian-8.1
  - name: centos-7.1
  - name: fedora-21

suites:
  - name: resources
    run_list:
      - recipe[systemd]
      - recipe[setup]
  - name: daemons
    excludes:
      - ubuntu-15.04
      - debian-8.1
      - centos-7.1
    run_list:
      - recipe[systemd::timesyncd]
      - recipe[setup::timesyncd]
      - recipe[systemd::journald]
      - recipe[setup::journald]
      - recipe[systemd::logind]
      - recipe[setup::logind]
      - recipe[systemd::resolved]
      - recipe[setup::resolved]
      - recipe[systemd::hostnamed]
      - recipe[systemd::journal_gatewayd]
