---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-15.04
  - name: debian-8.1
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[systemd]
      - recipe[setup]
    attributes:
