AllCops:
  Exclude:
    - Rakefile
    - Berksfile
    - metadata.rb
    - vendor/**/*
    - spec/**/*
    - test/**/*
Documentation:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
Metrics/LineLength:
  Max: 90
Metrics/MethodLength:
  Max: 15
